version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - '29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  topics:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Waiting until Kafka is ready'
      kafka-topics --bootstrap-server kafka:29092 --list
      echo -e 'Creating Kafka topic(s)'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic bidrag-vedtak --replication-factor 1 --partitions 1
      echo -e 'The following topic(s) are now available'
      kafka-topics --bootstrap-server kafka:29092 --list
      echo -e 'Ready to go!'
      "

  database:
      image: postgres:latest
      ports:
        - 5432:5432

      environment:
        POSTGRES_USER: cloudsqliamuser
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: default_database