apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  secureLogs:
    enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:bidrag/v1/bidragskrav"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  kafka:
    pool: {{ kafka.pool }}
  envFrom:
    - secret: bidrag-regnskap-sftp-private-key
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  gcp:
    sqlInstances:
      - name: {{ database.navn }}
        type: POSTGRES_14
        databases:
          - name: bidrag-regnskap-db
            envVarPrefix: DB
    buckets:
      - name: {{ bucket.navn }}
