name: bidrag-regnskap
ingresses:
  - https://bidrag-regnskap.intern.nav.no
kafka:
  pool: nav-prod
database:
  navn: bidrag-regnskap-prod
bucket:
  navn: bidrag-regnskap-prod
maskinporten:
  url: https://maskinporten.no
elin_subscription_key: bidrag-regnskap-elin-subscription-key-prod #TODO() Opprette key for prod
env:
  SKATT_URL: https://bidrag-stubs.intern.dev.nav.no #TODO()
  SKATT_HOST: bidrag-stubs.intern.dev.nav.no #TODO()
  TOPIC_VEDTAK: bidrag.vedtak
  TOPIC_PDL_AKTOR_V2: pdl.aktor-v2
  AKTOR_V2_GROUP_ID: aktor-v2.bidrag-regnskap
  BUCKET_NAME: bidrag-regnskap-prod
  SFTP_HOST: sftp.nav.no
  SFTP_SKAL_OVERFORE_FIL: true
  SAK_URL: https://bidrag-sak.prod-fss-pub.nais.io
  SAK_SCOPE: prod-fss.bidrag.bidrag-sak
  SAK_HOST: bidrag-sak.prod-fss-pub.nais.io
  PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  PERSON_HOST: bidrag-person.prod-fss-pub.nais.io
  MASKINPORTEN_SCOPES: "nav:bidrag/v1/bidragskrav"
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
  KONTERINGER_FORELDET_DATO: 2006-04
  SEND_KRAV_CRON: "-" #Deaktivert midlertidig TODO()
  RESEND_KRAV_CRON: "0 0 6 * * *" #Hver dag kl 06:00
  BEHANDLINGSSTATUS_CRON: "-" #Deaktivert midlertidig TODO()
  AVSTEMNING_CRON: "0 15 0 * * *" #Hver dag kl 00:15
  PALOSKJORING_CRON: "-" #Deaktivert midlertidig TODO()