CREATE TABLE IF NOT EXISTS oppdrag
(
    oppdrag_id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    stonad_type       text NOT NULL,
    vedtak_type       text NOT NULL,
    sak_id            text NOT NULL,
    kravhaver_ident   text,
    skyldner_ident    text NOT NULL,
    ekstern_referanse text,
    utsatt_til_dato   date,
    endret_tidspunkt  timestamp,
    engangsbelop_id   integer
);

CREATE INDEX oppdrag_stonad_type_index ON oppdrag (stonad_type);
CREATE INDEX oppdrag_kravhaver_ident_index ON oppdrag (kravhaver_ident);
CREATE INDEX oppdrag_skyldner_ident_index ON oppdrag (skyldner_ident);
CREATE INDEX oppdrag_ekstern_referanse_index ON oppdrag (ekstern_referanse);
CREATE INDEX oppdrag_engangsbelop_id_index ON oppdrag (engangsbelop_id);