CREATE TABLE IF NOT EXISTS overforing_konteringer
(
    overforing_id integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    kontering_id  integer   NOT NULL,
    referansekode text,
    feilmelding   text,
    tidspunkt     timestamp NOT NULL,
    kanal         text NOT NULL,

    CONSTRAINT feil_pkey PRIMARY KEY (overforing_id),
    CONSTRAINT feil_kontering_fkey FOREIGN KEY (kontering_id)
        REFERENCES konteringer (kontering_id) MATCH SIMPLE
);