CREATE TABLE IF NOT EXISTS palop
(
    palop_id           integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    kjoredato          date    NOT NULL,
    fullfort_tidspunkt timestamp,
    for_periode        text    NOT NULL,
    CONSTRAINT palop_pkey PRIMARY KEY (palop_id)
);