CREATE SEQUENCE delytelsesId_seq INCREMENT BY 1 START WITH 100000000;

CREATE TABLE IF NOT EXISTS oppdragsperioder
(
    oppdragsperiode_id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    oppdrag_id                     integer REFERENCES oppdrag,
    vedtak_id                      integer NOT NULL,
    vedtak_type                    text    NOT NULL,
    gjelder_ident                  text    NOT NULL,
    mottaker_ident                 text    NOT NULL,
    belop                          decimal NOT NULL,
    valuta                         text    NOT NULL,
    periode_fra                    date    NOT NULL,
    periode_til                    date,
    vedtaksdato                    date    NOT NULL,
    opprettet_av                   text    NOT NULL,
    konteringer_fullfort_opprettet boolean   DEFAULT false,
    delytelses_id                  integer   DEFAULT nextval('delytelsesId_seq'),
    aktiv_til                      date,
    opprettet_tidspunkt            timestamp DEFAULT current_timestamp,
    CONSTRAINT delytelses_id_unique UNIQUE (delytelses_id)
);

CREATE INDEX aktiv_til_index ON oppdragsperioder (aktiv_til);
CREATE INDEX oppdrag_id_index ON oppdragsperioder (oppdrag_id);
CREATE INDEX konteringer_fullfort_index ON oppdragsperioder (konteringer_fullfort_opprettet);
CREATE INDEX konteringer_fullfort_oppdrag_id_og_oppdragsperiode_id_index ON oppdragsperioder (oppdragsperiode_id, oppdrag_id, konteringer_fullfort_opprettet)