CREATE TABLE IF NOT EXISTS oppdrag
(
    oppdrag_id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    stonad_type             text    NOT NULL,
    kravhaver_ident         text,
    skyldner_ident          text    NOT NULL,
    ekstern_referanse       text,
    utsatt_til_dato         date,
    sist_oversendte_periode text,
    endret_tidspunkt        timestamp,
    engangsbelop_id         integer
);