CREATE TABLE IF NOT EXISTS overforing_konteringer
(
    overforing_id integer   PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    kontering_id  integer   REFERENCES konteringer,
    referansekode text,
    feilmelding   text,
    tidspunkt     timestamp NOT NULL,
    kanal         text      NOT NULL
);