CREATE SEQUENCE delytelsesId_seq INCREMENT BY 1 START WITH 100000000;

CREATE TABLE IF NOT EXISTS oppdragsperioder
(
    oppdragsperiode_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    oppdrag_id         integer REFERENCES oppdrag,
    vedtak_id          integer NOT NULL,
    gjelder_ident      text    NOT NULL,
    mottaker_ident     text    NOT NULL,
    belop              decimal NOT NULL,
    valuta             text    NOT NULL,
    periode_fra        date    NOT NULL,
    periode_til        date,
    vedtaksdato        date    NOT NULL,
    opprettet_av       text    NOT NULL,
    delytelses_id      integer DEFAULT nextval('delytelsesId_seq'),
    aktiv_til          date,

    CONSTRAINT delytelses_id_unique UNIQUE (delytelses_id)
);

CREATE INDEX aktiv_til_index ON oppdragsperioder (aktiv_til);
