CREATE TABLE IF NOT EXISTS konteringer
(
    kontering_id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    oppdragsperiode_id   integer REFERENCES oppdragsperioder,
    transaksjonskode     text    NOT NULL,
    overforingsperiode   text    NOT NULL,
    overforingstidspunkt timestamp,
    type                 text    NOT NULL,
    soknad_type          text,
    gebyr_rolle          text,
    sendt_i_palopsfil    boolean NOT NULL
);

CREATE INDEX konteringer_overforingstidspunkt_index ON konteringer (overforingstidspunkt);
