CREATE TABLE IF NOT EXISTS oppdrag
(
    oppdrag_id              integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    stonad_type             text    NOT NULL,
    kravhaver_ident         text,
    skyldner_ident          text    NOT NULL,
    referanse               text,
    utsatt_til_dato         date,
    sist_oversendte_periode text,
    endret_tidspunkt        timestamp,
    CONSTRAINT oppdrag_pkey PRIMARY KEY (oppdrag_id)
);