CREATE TABLE IF NOT EXISTS drift_avvik
(
    avvik_id      integer   NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    palop_id      integer,
    tidspunkt_fra timestamp NOT NULL,
    tidspunkt_til timestamp,
    opprettet_av  text,
    arsak         text,
    CONSTRAINT drift_avvik_pkrey PRIMARY KEY (avvik_id),
    CONSTRAINT drift_avvik_palop_fkey FOREIGN KEY (palop_id)
        REFERENCES palop (palop_id) MATCH SIMPLE
);